### PR TITLE
Binary

### PR DESCRIPTION
**Pull request by jeremyruppel**
This fixes a couple parts of `bin/mincer` that weren't working properly or were out of date.

### CODE REVIEW

**Comment by jeremyruppel** [comment]
Thanks @puzrin!

**Comment by puzrin** [comment]
Yeah, cli is really ancient. We ported it once, but never cared about seriously - nobody used it. Thank you for fixes.

**Comment by jeremyruppel** [comment]
I'm finding it pretty useful in some builds tasks I'm writing so thanks for keeping it around!

**Comment by puzrin** [comment]
Sould i publish new version or you plan more changes?

**Comment by jeremyruppel** [comment]
No more changes to the CLI. I have a (probable) bugfix I want to submit when I have the time, but no telling when I'll get to that. I can file an issue if you want to keep track of it.

**Comment by puzrin** [comment]
File it please, if it's important. Sometime ixti/me have mood to clear pending tails :)

**Comment by jeremyruppel** [comment]
Will do. Thanks!

**Pull request merged**
