### PR TITLE
Support HTML as part of the directive processor

### PR DESCRIPTION
**Pull request by mike-suggitt**
It would be really nice to bundle HTML files in the same way that CSS and JS are. It only requires a small change to the regex and the inclusion of the HTML MIME type.

```
var HEADER_PATTERN = new RegExp(
    '^(?:\\s*' +
    '(' +
    '(?:\/[*](?:\\s*|.+?)*?[*]\/)' + '|' +
    '(?:###\n(?:\\s*|.+?)*?\n###)' + '|' +

    '(?:\<!--(?:\\s*|.+?)*?--\>)' + '|' + //Include HTML files

    '(?:\/\/.*\n?)+' + '|' +
    '(?:#.*\n?)+' +
    ')*' +
    ')*', 'm');
```

Then simply set the mime type and plugin the direective processor

```
Mincer.registerMimeType('text/html', '.html');
Mincer.registerPreProcessor('text/html', Mincer.DirectiveProcessor);
```

I'd welcome your thoughts.

### CODE REVIEW

**Comment by puzrin** [comment]
I have no principal objection, except it worth to keep coding style intact - indent should be 2 spaces.

/cc @ixty ?

**Comment by ixti** [comment]
I'm not opposed to that I guess. Can you please keep original indentation in regexp though? I used it to see match groups.

**Comment by ixti** [comment]
Also, please add tests for that.

**Comment by puzrin** [comment]
Close - inactive for a long time

**Pull request closed without merging**
