### PR TITLE
Update to less 2.0

### LINKED ISSUE #167: Does not work with less 2.0
It seems the problem is in the less_engine.js 

`mincer/lib/mincer/engines/less_engine.js:87:36`
`[LessEngine] Cannot set property 'asset_data_uri' of undefined`

### PR DESCRIPTION
**Pull request by tikotzky**
This updates mincer to work with less 2.0

fixes #167

### CODE REVIEW

**Comment by puzrin** [comment]
@tikotzky i don't know why, but mincer examples are broken with 2.x.

**Comment by tikotzky** [comment]
@puzrin this seems to be the issue: http://stackoverflow.com/questions/26628309/less-v2-does-not-compile-twitters-bootstrap-2-x

I'll open a PR to update the example to the latest version of bootstrap.

**Comment by puzrin** [comment]
Ah, no problem then. Thanks a lot for info

**Comment by tikotzky** [comment]
just opened #182 to fix the example

**Pull request merged**
